### ISSUE TITLE
Enable sorting by column for Event Series/Event Instances Views

### ISSUE THREAD

**Issue by froboy** [ymcatwincities/openy_gated_content#100]
> As a content editor
> I want to sort event series and instances
> So that they're in the order that is convenient for me.

I'd propose we enable these sorts on these pages:

- /admin/content/events/instances
  - Title
  - Event Date
  - Created
  - Changed
- /admin/content/events/series
  - Title
  - Created
  - Changed

Sorting by "Series Starts" would be nice, but it seems that's [already been tried](https://www.drupal.org/project/recurring_events/issues/3160681) and is ~not possible~ much more complex.

**Comment by sarah-halby** [comment]
Corresponds to Jira ticket: https://openy.atlassian.net/browse/PRODDEV-182 - we will review during backlog grooming for future enhancements.

**Comment by sarah-halby** [comment]
Completed in 1.3 release.
