### ISSUE TITLE
Fix capitalization inconsistency in VY Titles and Empty messages

### ISSUE THREAD

**Issue by froboy** [ymcatwincities/openy_gated_content#101]
`Up next` should be `Up Next`

![Virtual_YMCA___Drush_Site-Install](https://user-images.githubusercontent.com/238201/105421110-2c23c400-5c07-11eb-8cec-6c0cfbc6d560.png)

`Live streams` -> `Live Streams`
`Virtual meetings` -> `Virtual Meetings`
`Virtual Meetings not found` -> `Virtual meetings not found.`
`Blog posts` -> `Blog Posts`

![Virtual_YMCA___Drush_Site-Install](https://user-images.githubusercontent.com/238201/105421463-c257ea00-5c07-11eb-80a0-b930e2590044.png)

Content sections should be title case when in titles, sentence case when not.

Upgrade path:
- easy - don't. Sites can manually update this text
- medium - if text exactly matches, then update it.

**Comment by sarah-halby** [comment]
Tied to Jira ticket: https://openy.atlassian.net/browse/PRODDEV-183?atlOrigin=eyJpIjoiODlhM2RjMGY3MzYzNDE1YmIzNzE4M2FhZmZmNDY4ODciLCJwIjoiaiJ9

**Comment by sarah-halby** [comment]
@froboy was this fixed in the PR? :-)

**Comment by froboy** [comment]
This is resolved.
