### ISSUE TITLE
Fix Activity Log Export when user has been removed

### ISSUE THREAD

**Issue by TomScarboroughYMCA** [ymcatwincities/openy_gated_content#102]
West Cook YMCA's Virtual Y site cannot export activity log data for January.

Repro Steps:

- Log into West Cook's Virtual Y site as Admin.
- Navigate to Manage > Virtual Y > Logs > Export log records
- Attempt to export a log for Date Start: "2021-01-01" to Date To: "2021-01-25"

In the browser, the error "The website encountered an unexpected error. Please try again later." will display and nothing else.

In the Watchdog logs, the attached stack trace is logged.
[ExportLogBug.txt](https://github.com/ymcatwincities/openy_gated_content/files/5868254/ExportLogBug.txt)

I believe this line of code in the LogArchiver class needs attention.  The entity object returned by $log->get('uid') is null, so the call to getEmail() on it is failing:
'user' => $log->get('uid')->target_id ? $log->get('uid')->entity->getEmail() : ''

** Y-USA is working on a patch.

**Comment by sarah-halby** [comment]
This corresponds to Jira ticket: https://openy.atlassian.net/browse/PRODDEV-188 @anpolimus will review when patch is ready from @TomScarboroughYMCA
