### ISSUE TITLE
Ask YouTube to limit related videos

### ISSUE THREAD

**Issue by froboy** [ymcatwincities/openy_gated_content#104]
While YouTube doesn't allow you us to disable related videos, [we can (as of today)](https://developers.google.com/youtube/player_parameters#rel) set `rel=0` to limit related videos to videos from the same author.

If a video is from YouTube, let's add this parameter to make things a little cleaner.

**Comment by sarah-halby** [comment]
Tied to user story in Jira: https://openy.atlassian.net/browse/PRODDEV-217

**Comment by anpolimus** [comment]
@froboy this is not a strait forward fix.
We are using MediaPlayer wrapper: https://github.com/p0rto/vue-video-wrapper that prepares data for Vimeo and Youtube.
It uses videoId as props and it is hard to push additional params for the URL construction.
There is an issue here, connected with a similar task: https://github.com/gajus/youtube-player/issues/63
We can try to help the maintainer to fix it and use it at our app.

**Comment by sarah-halby** [comment]
Completed in 1.3 release.
