### ISSUE TITLE
Feature Request: Attempt to route users to their destination at login

### ISSUE THREAD

**Issue by froboy** [ymcatwincities/openy_gated_content#106]
**Current behavior:**
When users attempt to use a link that's not the VY homepage they are presented with a login and then redirected back to the homepage.

To recreate:
- In a new session, visit https://sandbox-carnation-std-virtual-y.openy.org/virtual-ymca#/categories
- Click "Enter Virtual Y"
- Observe you're taken to https://sandbox-carnation-std-virtual-y.openy.org/virtual-ymca#/ instead of /categories

**Desired behavior:**
When a user attempts to visit a page we should keep track of the request and attempt to redirect the user back there upon login. If the user is not authorized to see the destination page, the appropriate error should be thrown with a suggestion to go back to the VY homepage.

- User attempts to visit https://virtual-y-demo.y.org/virtual-ymca#/categories/video
- User is presented with VY Login
- After successful auth, user is redirected to https://virtual-y-demo.y.org/virtual-ymca#/categories/video

Also posted at https://openy.atlassian.net/browse/PRODDEV-219

**Comment by sarah-halby** [comment]
@froboy assigned to the 5Jars team to review and address in sprint 4 which starts 2/24.

**Comment by sarah-halby** [comment]
Completed in 1.3 release.
