### ISSUE TITLE
Virtual YMCA Landing Page Small Banner Image is lost on 1.2 migration

### ISSUE THREAD

**Issue by froboy** [ymcatwincities/openy_gated_content#107]
**To recreate:**
- Take a site on VY 1.1, add an image to the "Small Banner" paragraph on the Virtual YMCA Landing Page
- Update to 1.2, observe the image is deleted, but the title and description are migrated.

![Edit_Landing_Page_Virtual_YMCA___Missouri_Valley_Family_YMCA](https://user-images.githubusercontent.com/238201/107092942-07644a80-67ca-11eb-8795-48fc1cf29548.png)

**Expected behavior**
- the image is migrated to its new field along with the title and description

**Comment by sarah-halby** [comment]
@froboy - has this been reviewed by @anpolimus ? If so, can this be closed?

**Comment by froboy** [comment]
Yes, this has been reviewed and merged into 1.2.3.
