### ISSUE TITLE
Error on saving VY Landing Page

### ISSUE THREAD

**Issue by froboy** [ymcatwincities/openy_gated_content#110]
Seems related to #49.

- Edit existing landing page
- Save
- Observe errors

> Warning: Illegal string offset '_original_delta' in Drupal\Core\Field\WidgetBase->extractFormValues() (line 381 of core/lib/Drupal/Core/Field/WidgetBase.php).
> Warning: implode(): Invalid arguments passed in Drupal\openy_gated_content\Plugin\Field\FieldWidget\GatedContentPermissionsFieldWidget->massageFormValues() (line 123 of modules/contrib/openy_gated_content/src/Plugin/Field/FieldWidget/GatedContentPermissionsFieldWidget.php). 

I've been able to resolve the second warning with this at line 119 of `modules/contrib/openy_gated_content/src/Plugin/Field/FieldWidget/GatedContentPermissionsFieldWidget.php`:
```
    // If this is not gated content $values = [0=>'0'] in which case we return.
    if (array_key_first($values) === 0) return;
```

But I don't know why the first is happening. I also tried re-saving `/admin/structure/types/manage/landing_page` just in case there was an issue with the config, but that didn't resolve the issue. This does NOT seem to be happening on the sandbox, even with errors turned on, so I'm not sure what the issue is.

**Comment by anpolimus** [comment]
Hi, @froboy it is happening, because we are replacing a string field value with a list array.
Everything works fine except for such empty values. Sometimes it is the empty string, sometimes - array with zero first item

**Comment by froboy** [comment]
@anpolimus so it sounds like `Warning: Illegal string offset '_original_delta'` will continue to exist (we just have to hide it in prod, as usual), but the fix above resolves `Warning: implode(): Invalid arguments passed`?

**Comment by anpolimus** [comment]
Yes, you are right.

**Comment by sarah-halby** [comment]
@hamrant please let me know if we are good to close this issue given the merged PRs above.

**Comment by hamrant** [comment]
@sarah-halby yep, this one fixed
