### ISSUE TITLE
Category listing page only shows 8 videos and no pager

### ISSUE THREAD

**Issue by froboy** [ymcatwincities/openy_gated_content#115]
**Observed behavior**
The listing of videos in a certain category only displays 8 videos, even if more exist.

![image(1)](https://user-images.githubusercontent.com/238201/108113265-ed91f580-705c-11eb-84b0-c5b1e18b564f.png)

**Expected behavior**
If more than 8 videos exist, a pager should appear.

**To recreate**
- Assign more than 8 videos to a Category
- Go to Categories > Your Category > "More" (to the right of "Videos")
- Observe only 8 videos appear

https://openy.atlassian.net/browse/PRODDEV-238

**Comment by hamrant** [comment]
PR with fix - https://github.com/fivejars/openy_gated_content/pull/272

**Comment by sarah-halby** [comment]
Fixed in 1.2.4
