### ISSUE TITLE
If duration field is empty or 0, hide it on the display

### ISSUE THREAD

**Issue by froboy** [ymcatwincities/openy_gated_content#116]
![Virtual_YMCA](https://user-images.githubusercontent.com/238201/108310135-73ef2a00-7178-11eb-995d-d988ba8b780a.png)

**Comment by sarah-halby** [comment]
Jira Ticket: https://openy.atlassian.net/browse/PRODDEV-242 - @froboy we've added this to the backlog to address at a future date.

**Comment by sarah-halby** [comment]
This was completed in March 2021. I am closing this ticket.
