### ISSUE TITLE
Virtual-y Shared Content - Wrong token being updated in Shared content source entities.

### ISSUE THREAD

**Issue by rajeshkeladimath** [ymcatwincities/openy_gated_content#118]
Hi team,

We created the "shared content server" and then created the "shared content source" by copying the token generated from previous step. But it gets updated wrongly. And hence we are unable to pull the contents from the remote sources. Could you please check this issue and resolve ?

![image1](https://user-images.githubusercontent.com/8415953/108497897-238bdf80-72d2-11eb-9da6-f9b27e22f1cb.png)
![image2](https://user-images.githubusercontent.com/8415953/108497908-2555a300-72d2-11eb-8b11-2e6be56da48c.png)

**Comment by froboy** [comment]
@rajeshkeladimath It looks like the team might need some more information to help you troubleshoot this and #86. If you'd like to join the Open Y Slack to discuss these issues with the team more directly, feel free to submit a request at https://openy.org/contact/slack_access_request.

**Comment by rajeshkeladimath** [comment]
Okay.

**Comment by hamrant** [comment]
@rajeshkeladimath please check these steps https://github.com/fivejars/openy_gated_content/pull/122 (how to setup server and client), no need to copy token manually, this should work automatically. Please check that client and server updated to the latest VY version.

**Comment by rajeshkeladimath** [comment]
Okay. Thank you.

**Comment by sarah-halby** [comment]
Per the discussion in Slack, this issue has been resolved: https://openy.slack.com/archives/C01715RK630/p1615987969002600 Closing this ticket.
