### ISSUE TITLE
Site Owners and Admins cannot input the time component of the Activity Log From/To filter

### ISSUE THREAD

**Issue by TomScarboroughYMCA** [ymcatwincities/openy_gated_content#119]
Repro Steps:

- Log into any Virtual Y site as Site Owner or Administrator
- Navigate to Manage > Virtual Y > Logs
- Specify a Date Start and Date End

Note that, despite the format instruction underneath the input fields stating "Format: YYYY-MM-DD HH:MM:SS", spaces are not accepted so there is no way to specify input such as "2021-02-22 10:00:00"

Site Owner contacting me wishing to see today's activity. She is able to do so by specifying a Date Start only without a Date End, but having the fidelity to specify times is something she wants, since the format instructions suggests this is possible.

**Comment by TomScarboroughYMCA** [comment]
The ui-datepicker control does not provide for selecting a time for a given date, and the input masking on the text fields will not allow inserting a space, *but* a workaround is to create the filter text in notepad, then copy/paste the values into the fields. The text will paste into the fields as originally typed, with spaces. This allows filtering on a specific day using Date Start "2021-02-22 00:00:00" and Date End "2021-02-22 23:59:59", for example.

A DateTime picker that extends the JQuery datepicker is available at https://trentrichardson.com/examples/timepicker/. This permits time entry and provides a pair of slider controls for graphically picking hours and minutes.

**Comment by froboy** [comment]
I found that the dates are filterable without a space between the date and time, but there's still a mismatch in instructions here which needs to be worked out. 
![Virtual_Y_Logs___Eugene_Family_YMCA](https://user-images.githubusercontent.com/238201/108860400-c5058080-75b3-11eb-9078-83e106747538.png)

**Comment by sarah-halby** [comment]
@TomScarboroughYMCA I've added this issue to the backlog: https://openy.atlassian.net/browse/PRODDEV-251

**Comment by TomScarboroughYMCA** [comment]
Per Scott and Avi, this search is date-only, so fix the help text to remove the timestamp from the date formatting.

**Comment by sarah-halby** [comment]
This was included in the 1.4 release in May 2021.
