### ISSUE TITLE
"Event Start Time" field displayed incorrectly

### ISSUE THREAD

**Issue by jwtechdesign** [ymcatwincities/openy_gated_content#12]
When creating a "Virtual Meeting" or "Live Stream" (only 2 I tested at this point), the displayed "Start Time" does not match what is entered into the field itself - the displayed time is consistently 5 hours behind.  

Tested on a local site, as well as the sandbox site (https://sandbox-carnation-std-virtual-y.openy.org).

![image](https://user-images.githubusercontent.com/32372465/89205790-e2beba00-d57d-11ea-8132-f6d3ac66956d.png)

Timezone setting on local site: "Chicago" (Central timezone)
Timezone setting on sandbox site: UTC

I'm physically in the Central timezone (Nashville, TN, USA)

**Comment by hamrant** [comment]
From slack communication:
![Screenshot from 2020-08-05 11-15-09](https://user-images.githubusercontent.com/13733670/89388666-0106f000-d70d-11ea-9061-443fec89d11b.png)

@jwtechdesign can you try the cache clear? Maybe this can fix the problem without entities re-saving

**Comment by hamrant** [comment]
@paige-kiecker let's close this issue
