### ISSUE TITLE
VY "top menu" bugs in Lily and Rose

### ISSUE THREAD

**Issue by froboy** [ymcatwincities/openy_gated_content#120]
## Lily: 
- Top menu is not accessible in iPad landscape orientation.

![Virtual_YMCA___Eugene_Family_YMCA_—__Private_Browsing_](https://user-images.githubusercontent.com/238201/109208953-9680d480-7770-11eb-900f-9cdf8b94003f.png)

Reproducible on https://sandbox-lily-std-virtual-y.openy.org/

## Rose:
- Top menu overlaps logo
![Virtual_YMCA___Drush_Site-Install_—__Private_Browsing_](https://user-images.githubusercontent.com/238201/109209354-1018c280-7771-11eb-81cb-aad37593ad47.png)

- on scroll, top menu and nav have extra space

![Virtual_YMCA___Drush_Site-Install_—__Private_Browsing_](https://user-images.githubusercontent.com/238201/109209448-2aeb3700-7771-11eb-955c-d5f41786da90.png)

reproducible at https://sandbox-rose-std-virtual-y.openy.org/

https://openy.atlassian.net/browse/PRODDEV-248

**Comment by anpolimus** [comment]
It was fixed in https://github.com/fivejars/openy_gated_content/pull/332
We can close it.
