### ISSUE TITLE
"Virtual Y Permissions" option is not saved.

### ISSUE THREAD

**Issue by vikasbn0** [ymcatwincities/openy_gated_content#121]
Hi, 

On creating a new "Video" or an "Event Series" or editing an existing one, the "**Virtual Y Permissions**" field's option is not saved, i.e if we select a value from the "Virtual Y Permissions" field list and save the node, upon editing the node the value is not shown as selected. This is in version 1.2.3. 
I tested in sandbox site, there also the issue is present.

Here is a screenshot where the "Virtual YMCA" is selected in the "Virtual Y Permissions" field.
![Screenshot from 2021-02-26 18-48-10](https://user-images.githubusercontent.com/49018287/109305101-433b7e80-7863-11eb-9c0a-0d5bf894e9f2.png)

After saving the node and then editing it the option is not shown as selected.

![Screenshot from 2021-02-26 18-48-29](https://user-images.githubusercontent.com/49018287/109305428-b218d780-7863-11eb-8035-c058f6cb4c35.png)

**Comment by sarah-halby** [comment]
@vikasbn0 our lead developer is out for a couple of days. Have you reached out to the virtual_y channel on slack to see if anyone else is experiencing this issue and can provide more details?

**Comment by vikasbn0** [comment]
I am sorry but I am not in the Slack channel, can you please provide a link to join?

**Comment by froboy** [comment]
@vikasbn0 this is resolved in https://github.com/fivejars/openy_gated_content/pull/273 and has been pushed to 1.2.4. Please try updating to that code. See the PR and https://community.openymca.org/t/virtual-y-1-2-x-tips-troubleshooting/909 for notes.
