### ISSUE TITLE
For ReClique CORE CRM Y's, Virtual Y role is not the default new user role if no Permissions Mapping defined.

### ISSUE THREAD

**Issue by TomScarboroughYMCA** [ymcatwincities/openy_gated_content#122]
When a Virtual Y site that uses ReClique CORE as the CRM does not have any Permission Mappings configured, the default role should be **Virtual YMCA**. Right now, no role is assigned for newly-created users.

Repro Steps:

- Go to https://northpennymca-azure-stage.y.org (or equivalent Virtual Y site that uses ReClique CORE crm).
- Verify there are no Permission Mappings present in the Reclique authentication provider configuration.
- Create a new user in the system by logging in with an member's email address for that that is not already in the system 
- example used for North Penn: nan_dec@yahoo.com.
- If this user is already present in People, delete that user from People to enable the test.
- Upon login, note that content categories are viewable and clickable, but no Blog or Video content will be visible or clickable.

Acceptance Criteria:

When a new user is created in the Virtual Y using a member email address registered in the ReClique CORE crm, and no Permission Mappings are entered on that Virtual Y site, the default role should be **Virtual YMCA**.

**Comment by sarah-halby** [comment]
@froboy this ticket was updated in Jira - can you please review the most recent comment? https://openy.atlassian.net/browse/PRODDEV-259

**Comment by sarah-halby** [comment]
@TomScarboroughYMCA this was addressed with the VY 1.3 release. I'm going to close this ticket.
