### ISSUE TITLE
Update Virtual Event and Livestreams default text to be configurable

### ISSUE THREAD

**Issue by froboy** [ymcatwincities/openy_gated_content#123]
> As an administrator of Virtual Y,
> I want to configure the default text on my virtual event and livestream pages,
> so that it can match the terminology set elsewhere on the site

![image](https://user-images.githubusercontent.com/238201/109517477-f0361700-7a6e-11eb-9ff1-1365efcaa92b.png)

https://openy.atlassian.net/browse/PRODDEV-256

**Comment by sarah-halby** [comment]
@froboy this has been assigned to QA to review.

**Comment by sarah-halby** [comment]
@froboy this has been reviewed by QA and is ready for your review and approval. If so, this will be included in the 1.3 release.

**Comment by froboy** [comment]
Confirmed. https://github.com/fivejars/openy_gated_content/pull/267
