### ISSUE TITLE
Virtual Meetings (series and instances) are not showing up on the calendar 

### ISSUE THREAD

**Issue by rdwash** [ymcatwincities/openy_gated_content#125]
When entering recurring virtual meetings (exercise classes), the virtual meeting, or instances of it, may not show up on the schedule calendar. It is not known why some virtual meetings are showing up and some are not. So far, only one YMCA has raised this issue as, for instance, none of their "Saturday" classes are showing on the calendar and some instances of a "Friday" class aren't showing on the calendar. Please see the screenshots below.

**Here's a virtual meeting setup for Fridays through March 2021:**
![image](https://user-images.githubusercontent.com/5083127/109672746-f265a780-7b3a-11eb-8b8a-831f91d4ca5f.png)

![image](https://user-images.githubusercontent.com/5083127/109674990-fc88a580-7b3c-11eb-95b7-bcaa5594d2e3.png)

**Also, here's a virtual meeting setup for Saturdays:**
![image](https://user-images.githubusercontent.com/5083127/109673853-0c53ba00-7b3c-11eb-9d8f-3dc493834b75.png)

![image](https://user-images.githubusercontent.com/5083127/109674603-aae01b00-7b3c-11eb-87fa-6ceb2452b2f3.png)

**Comment by sarah-halby** [comment]
@rdwash what platform is this Y using for virtual meetings? We can take a look at this issue and see when we can work into a future sprint cycle to address it. Currently, our sprint cycle is full until March 10th, so we'll either need to wait to prioritize this work or get approval to remove the current workload from this sprint.

**Comment by rdwash** [comment]
@sarah-halby The Y is on the latest point release from VY 1.2.3. I also attempted to add a new weekly virtual meeting for Fridays and same thing. We'll continue to investigate on our end.

**Comment by rdwash** [comment]
@sarah-halby We think we've narrowed the issue down to a "display limit", possibly 50 items, issue for the calendar for any week. As we move virtual meetings in and out of a given week, we're noticing virtual meetings falling off as others are added, depending the instance times configured.

**Comment by sarah-halby** [comment]
@rdwash did increasing the display limit on your local environment fix this issue? If so, what did you update the limit to?

**Comment by rdwash** [comment]
@sarah-halby yes increasing the limit worked...we updated the limit to 100 to start.

**Comment by sarah-halby** [comment]
Thanks for confirming @rdwash - I'm going to close this ticket as there is a workaround available for the community. I've added this enhancement to our backlog to adjust the default moving forward.

**Comment by hamrant** [comment]
The issue was fixed in https://github.com/fivejars/openy_gated_content/pull/320 by switching from JSON API to a custom controller for schedule page

cc @sarah-halby @rdwash
