### ISSUE TITLE
"More" button on dashboard should be more noticable

### ISSUE THREAD

**Issue by froboy** [ymcatwincities/openy_gated_content#131]
Some users have reported not understanding that there are more videos than the ones listed on the homepage. Let's help them find them and also make the link more accessible, as folks with color blindness might not know "More" is a button since the link is only indicated by color and nothing else.

Before:
![Virtual_YMCA___Virtual_YMCA](https://user-images.githubusercontent.com/238201/113452896-948ede80-93ca-11eb-98c6-9a97d741462c.png)

Recommendation:
![Virtual_YMCA___Virtual_YMCA](https://user-images.githubusercontent.com/238201/113454224-55ae5800-93cd-11eb-828d-75d186448ad7.png)

**Comment by sarah-halby** [comment]
@anpolimus - adding this to the backlog. Can you review when you have the chance?

**Comment by sarah-halby** [comment]
@froboy this will be closed on May 11 when this is included in the next major release.
