### ISSUE TITLE
For Virtual Y sites using Y-USA Provider, members with updated Daxko barcodes cannot log into the VY site.

### ISSUE THREAD

**Issue by TomScarboroughYMCA** [ymcatwincities/openy_gated_content#132]
For Virtual Y sites that manage their members in Daxko and also use the Y-USA Provider to authenticate users, when members get a new Daxko barcode and they attempt to log in with that barcode, they will see the "White screen of death" with error message "The website encountered an unexpected error. Please try again later."

**Repro steps:**
Existing Daxko user gets a new barcode, but still has the same user name. A new email address may be present as well.
Daxko user attempts to sign in to the Virtual Y site using this new barcode
The new barcode will initiate the workflow for creating a new Virtual Y user. The SQL insert will fail due to a data integrity error since the username is already present in the database.

**Acceptance Criteria:**
Since the new barcode is valid for the user, but an existing user already exists in the Virtual Y with an older barcode, an error message must be displayed instead of the "White screen of death".

**Comment by sarah-halby** [comment]
@anpolimus is this ready for the May 11 release in VY as well?

**Comment by anpolimus** [comment]
We can close it since PR was merged and released.
