### ISSUE TITLE
VueJS app should correctly process dates, coming from the Drupal backend in the UNIX timestamp format

### ISSUE THREAD

**Issue by NightHunterSV** [ymcatwincities/openy_gated_content#133]
There is a setting in Drupal, which controls the format of date values, coming from the backend when using REST or JSON API. For most sites, which development was started from Drupal 8.4, this setting is already set to output dates in the RFC3339 format, and this is correctly processed by the dayjs library, used in the VY VueJS app since 1.2.4. But there is another option, available through the config, and met on some projects, started before Drupal 8.4, or required by some integrations -- is the UNIX timestamp format, and the dayjs library processes date in this format as a milliseconds -- so we get the wrong date on the frontend side.

Config option to change the output format:
`serialization.settings`
```bc_timestamp_normalizer_unix: true|false```
`true` -- UNIX timestamps
`false` -- date in RFC3339 format

The issue when the date format was changed
https://www.drupal.org/project/drupal/issues/2768651

Dayjs documentation to create date object from the input value:
https://day.js.org/docs/en/parse/string -- from ISO 8601 format string (RFC3339 is just a more strict format)
https://day.js.org/docs/en/parse/unix-timestamp -- from the UNIX timestamp

**Comment by sarah-halby** [comment]
@anpolimus will this be included in the May 11, 1.4 VY release?

**Comment by sarah-halby** [comment]
@anpolimus any update on this ticket? cc @gianni-imagex

**Comment by anpolimus** [comment]
@NightHunterSV please double check. I thought, we have fixed it in 1.3

**Comment by NightHunterSV** [comment]
@anpolimus, right, the issue now resolved in the linked PR: https://github.com/fivejars/openy_gated_content/pull/309
cc @sarah-halby

**Comment by sarah-halby** [comment]
Thank you @NightHunterSV & @anpolimus - closing this ticket.
