### ISSUE TITLE
Shared Content "Virtual Y video" tab should be default

### ISSUE THREAD

**Issue by froboy** [ymcatwincities/openy_gated_content#139]
> As a Virtual Y Admin/Editor
> When I fetch shared content
> I want to not be confused. 

Navigating to Virtual Y > Shared Content > Fetch brings up the "Virtual Y blog post" tab by default, which is confusing because there's very little content on that page. The "Virtual Y video" tab should be the default.

![Shared_content](https://user-images.githubusercontent.com/238201/119160676-1fc93f80-ba1e-11eb-8eb5-0342c79e3c8d.png)

**Comment by sarah-halby** [comment]
@gianni-imagex could you please get this added as a ticket in Jira? It looks like Anastasiia and Anatoliy have already tested it, but I want to make sure the master test plan gets updated. Please add the Jira ticket link to the comments for reference.

**Comment by gianni-imagex** [comment]
@sarah-halby Yep, we have a ticket here: https://openy.atlassian.net/browse/PRODDEV-358 
It was assigned to Stacey this morning for addition to the master test plan.

**Comment by sarah-halby** [comment]
Thank you @gianni-imagex this will be in the 1.4.1 release.
