### ISSUE TITLE
Make stream autoplay configurable.

### ISSUE THREAD

**Issue by anpolimus** [ymcatwincities/openy_gated_content#141]
In our last release, we've hard-coded the initial state of the stream to pause.
https://github.com/ymcatwincities/openy_gated_content/commit/df558cbce57bd94dbfed731e23966ff0b2392030

It was done for the log feature. Click on the play button fires stream start action in the Virtual Y log system.

Many of our Y's had video streams in auto play mode by default and are upset now.

For now, we can write a little patch. For the future, it is better to have this option configurable. We can add checkbox at the VY setting page, called `Stream autoplay mode`

**Autoplay mode**
We are setting autoplay to true + firing video start event during component load during a load of a video component.

**Pause mode**
We are setting autoplay to false + firing video start event by the button click event.

**Comment by gianni-imagex** [comment]
https://openy.atlassian.net/browse/PRODDEV-362

**Comment by anpolimus** [comment]
Since Jira ticket is closed, we can close this issue.
