### ISSUE TITLE
jsonapi_image_styles can't be installed for Drupal core 9.0.x or and ^9.1 || ^9.2

### ISSUE THREAD

**Issue by podarok** [ymcatwincities/openy_gated_content#145]
See  https://www.drupal.org/project/jsonapi_image_styles/issues/3213878

**Comment by anpolimus** [comment]
Got it. Thanks

**Comment by podarok** [comment]
https://www.drupal.org/project/jsonapi_image_styles/issues/3223536 please, support with RTBC @hamrant @anpolimus

**Comment by sarah-halby** [comment]
@anpolimus & @hamrant what are the next steps for this? Is it ready to be added to a release or should we hold? cc @KylieAldridge

**Comment by hamrant** [comment]
@sarah-halby in this issue - https://www.drupal.org/project/jsonapi_image_styles/issues/3223536  @podarok requested Co-maintainer access to the `jsonapi_image_styles` project.

Next step, merge this patch - https://www.drupal.org/project/jsonapi_image_styles/issues/3213878 (possible only with maintainer role)

**Comment by sarah-halby** [comment]
@hamrant Got it - thank you for the clarification. :-) We'll wait until we hear from @podarok about the maintainer request and release a point release if necessary. @shelleygoetz - if this isn't in Jira, could you please add it for tracking purposes?

**Comment by sarah-halby** [comment]
@podarok & @hamrant here is the corresponding Jira ticket: https://openy.atlassian.net/browse/PRODDEV-404

**Comment by podarok** [comment]
Fixed https://www.drupal.org/project/jsonapi_image_styles/releases/2.0.0-beta3
