### ISSUE TITLE
Personal training module missing STUN server info

### ISSUE THREAD

**Issue by froboy** [ymcatwincities/openy_gated_content#146]
https://github.com/ymcatwincities/openy_gated_content/blob/master/modules/openy_gc_personal_training/README.md#1on1-virtual-meetings-server-configuration

> If you want to enable 1on1 Virtual Meetings module, you have to setup 3 additional services at your server or somewhere in the internet.

But the bullet that should have information about the STUN server is empty.

**Comment by anpolimus** [comment]
Since @froboy prepared a fix and it was merged in 1.5 we can close it.

**Comment by anpolimus** [comment]
@froboy thank you again!
