### ISSUE TITLE
Add check the code is run on the Node entity page

### ISSUE THREAD

**Issue by NightHunterSV** [ymcatwincities/openy_gated_content#147]
We should check before, that the node is a Drupal\node\NodeInterface, or, at least, FieldableEntityInterface.
We've got the error on this string at some project, where the route's 'node' parameter is a string.

https://github.com/ymcatwincities/openy_gated_content/blob/50dfae4a8970cceb8529612f6c29dad849296d78/openy_gated_content.module#L112

**Comment by anpolimus** [comment]
@NightHunterSV thank you.
You are totally right.

**Comment by sarah-halby** [comment]
@anpolimus what is the estimate for this fix and what are the next steps?

**Comment by anpolimus** [comment]
@sarah-halby we will do it in scope of our current ticket.

**Comment by anpolimus** [comment]
@sarah-halby here is the fix ^^

**Comment by sarah-halby** [comment]
@anpolimus & @hamrant are we good to close this ticket then?

**Comment by hamrant** [comment]
@sarah-halby yep
