### ISSUE TITLE
Status report shows mismatched entity and field definitions

### ISSUE THREAD

**Issue by AndreyMaximov** [ymcatwincities/openy_gated_content#148]
The storage doesn't seem to be properly provisioned.

On the Virtual Y websites (`openy_gated_content` versions `1.2.4`, `1.3`) the following messages appear in the status report
![image](https://user-images.githubusercontent.com/5453109/128842482-c359790d-63d8-4ee1-802e-61c1856dc192.png)

That seems to be related to the upgrade path. The websites experiencing the issue were upgraded from earlier versions.

**Comment by froboy** [comment]
This issue has existed since November, as per [this Slack thread](https://openy.slack.com/archives/C01715RK630/p1604356096165700) and possibly [even earlier](https://openy.slack.com/archives/C6G4ZTLVC/p1602702907205000).

**Comment by anpolimus** [comment]
A ticket was raised for this issue: https://openy.atlassian.net/browse/PRODDEV-411

**Comment by sarah-halby** [comment]
@froboy this was completed in the VY 1.5.1 point release on 9/7
