### ISSUE TITLE
In Virtual Y, the "More ->" link is displayed for a Video category even if <= 8 videos exist for that category.

### ISSUE THREAD

**Issue by TomScarboroughYMCA** [ymcatwincities/openy_gated_content#151]
In Virtual Y, the "More ->" link is displayed for a Video category even if <= 8 videos exist for that category. This is observable in the [Carnation sandbox site](https://sandbox-carnation-std-virtual-y.openy.org/) when viewing the [Barre category](https://sandbox-carnation-std-virtual-y.openy.org/virtual-ymca#/category/e5e34d07-ae65-43d5-ba1d-0f835857da28), which contains a single video but still displays the More link.

**Comment by sarah-halby** [comment]
@shelleygoetz could you get a ticket added to the VY backlog for this issue and add the Jira ticket link here, please?

**Comment by sarah-halby** [comment]
@TomScarboroughYMCA here is the PR link: https://github.com/fivejars/openy_gated_content/pull/386 - this will be released in the next release in November (if we do a point release before then, it will be included earlier). Please grab it if you and your clients want it sooner. :-)  Closing this ticket.
