### ISSUE TITLE
Virtual Y: Archived logs do not record the name of content viewed

### ISSUE THREAD

**Issue by TomScarboroughYMCA** [ymcatwincities/openy_gated_content#152]
The current version of Virtual Y's logging does not include Content Title information in the exported log file.

**Repro Steps**

- Sign into a Virtual Y site migrated to the latest version (VY YCloud 0.12.1), such as Kenosha (https://kenoshaymca.y.org/) as of 8/18/2021.
- View the activity recorded in the online logs at Manage > Virtual Y > Logs.
- Create a new log export to capture today's activity to CSV.
- View the same timeframe as viewed online in the CSV file.
- Note the column labeled "Content Title" contains no title data.

Alternatively,

- Log into the Carnation sandbox site (https://sandbox-carnation-std-virtual-y.openy.org/) with Open Y Virtual YMCA Log module enabled.
- Perform activity.
- View that activity at Manage > Virtual Y > Logs.
- Export that day's activity to a file.
- View the file and note the missing Content Titles.

Refer to the following attachments:

- PRE-MIGRATION virtual-y-logs-2021-08-17-2021-08-18-11-39-06.csv (from NorthPenn Virtual Y - taken today prior to their migration)
- POST-MIGRATION virtual-y-logs-2021-08-17-2021-08-17-23-59-59.csv (from Kenosha Virtual Y)
- virtual-y-logs-2021-08-01-2021-08-18-16-12-09.csv - downloaded from the Carnation Sandbox site today - shows empty content title column
- Sandbox site - my activity.png - shows what I did on the Carnation sandbox site - titles are recorded.
- Sandbox site - my archived activity.png - the exported activity from today - no content titles present.
![Sandbox site - my activity](https://user-images.githubusercontent.com/71293659/129938205-31d9dcdd-dba0-4123-89ae-7c892a6deb7c.png)
![Sandbox site - my archived activity](https://user-images.githubusercontent.com/71293659/129938207-142eef42-5fcd-4669-b154-00a2f5bf508a.png)
[virtual-y-logs-2021-08-01-2021-08-18-16-12-09.csv](https://github.com/ymcatwincities/openy_gated_content/files/7008816/virtual-y-logs-2021-08-01-2021-08-18-16-12-09.csv)
[POST-MIGRATION virtual-y-logs-2021-08-17-2021-08-17-23-59-59.csv](https://github.com/ymcatwincities/openy_gated_content/files/7008817/POST-MIGRATION.virtual-y-logs-2021-08-17-2021-08-17-23-59-59.csv)
[PRE-MIGRATION virtual-y-logs-2021-08-17-2021-08-18-11-39-06.csv](https://github.com/ymcatwincities/openy_gated_content/files/7008818/PRE-MIGRATION.virtual-y-logs-2021-08-17-2021-08-18-11-39-06.csv)

**Comment by sarah-halby** [comment]
This has been QA'd and added to the master test plan. https://openy.atlassian.net/browse/PRODDEV-421 - this will be included in the 1.5.1 point release.

**Comment by sarah-halby** [comment]
@TomScarboroughYMCA this was included in the point release on 9/7. I'm closing this ticket.
