### ISSUE TITLE
Error at hook_update during attempt to update to 1.5.1

### ISSUE THREAD

**Issue by anpolimus** [ymcatwincities/openy_gated_content#157]
Hi.
We have an issue at hook_update from the last release.
`openy_gated_content_update_8018` fails during an attempt to update D9 project from 1.4 to the 1.5.1

[error]  Argument 2 passed to Drupal\Core\Field\FieldStorageDefinitionListener::onFieldStorageDefinitionUpdate() must implement interface Drupal\Core\Field\FieldStorageDefinitionInterface, null given, called in /var/www/docroot/core/lib/Drupal/Core/Entity/EntityDefinitionUpdateManager.php on line 233 
>  [error]  Update failed: openy_gated_content_update_8018 
>  [notice] Update started: config_split_update_8002
>  [notice] Update completed: config_split_update_8002
 [error]  Update aborted by: openy_gated_content_update_8018

**Comment by shelleygoetz** [comment]
Issue was added to Jira here: https://openy.atlassian.net/browse/PRODDEV-450

**Comment by sarah-halby** [comment]
This went out for the 1.5.2 point release last week. Closing this ticket.
