### ISSUE TITLE
Day of Week labels shifted on week of DST change

### ISSUE THREAD

**Issue by froboy** [ymcatwincities/openy_gated_content#166]
![Virtual_YMCA___Drush_Site-Install](https://user-images.githubusercontent.com/238201/138714341-8174955b-c842-4566-bc7d-a6b62ec0b44a.png)

Guess who's back, back again. DST is back, tell your friends.

To reproduce:

- Visit https://sandbox-carnation-std-virtual-y.openy.org
- Log in
- Go to the Schedule
- Advance the weeks to November 7

**Comment by sarah-halby** [comment]
This was resolved in the 1.6 VY updated on Nov 9.
