### ISSUE TITLE
Replace deprecated node-sass package on the APP.

### ISSUE THREAD

**Issue by anpolimus** [ymcatwincities/openy_gated_content#171]
Hi.
`node-sass` package is deprecated.
We have to migrate to sass compiler.
https://github.com/ymcatwincities/openy_gated_content/blob/master/js/gated-content/package.json#L43

Here is an information about that.
https://www.npmjs.com/package/node-sass

**Comment by sarah-halby** [comment]
@shelleygoetz please open a Jira ticket for this issue in the prod dev board.

**Comment by shelleygoetz** [comment]
@sarah-halby Jira ticket added: https://openy.atlassian.net/browse/PRODDEV-482

**Comment by sarah-halby** [comment]
This will be added to the VY 1.6.1 release later in December.
