### ISSUE TITLE
Drupal 9 Multiple Categories Don't Work in Drupal 9 Alpha

### ISSUE THREAD

**Issue by dwells-tn** [ymcatwincities/openy_gated_content#29]
**Issue:** [New multiple category just released in Virtual Y 0.14](https://openy.slack.com/archives/C01715RK630/p1599579042033300) are not yet present in Drupal 9 Sandbox.

**Steps to Reproduce:**

- Go to Virtual Video and add content type OR edit existing video on Sandbox
- Add a second category
- See the initial category disappear

I tested this with this video: https://sandbox-carnation-std-virtual-y-d9.openy.org/virtual-ymca#/video/c50c68c3-82fe-486f-8a0b-e9f1ca8604ac

Present on other themes as well.

**Comment by sarah-halby** [comment]
@podarok can you review this item and see if it is an issue in Drupal 9.0 & 9.1? I'll get it added to Jira as a bug.

**Comment by podarok** [comment]
Seems like on the latest Virtual Y this is not anymore an issue
I was able to add BootCamp as a secondary category and it does work without any issues @sarah-halby 

![image](https://user-images.githubusercontent.com/563412/105023691-f1c5f580-5a53-11eb-9586-d5c0d0adce96.png)

**Comment by sarah-halby** [comment]
@hamrant & @anpolimus this has been tested and confirmed working by @podarok. If you believe this is good to go, please close this issue. If it is not, please provide additional context for testing.

**Comment by hamrant** [comment]
@sarah-halby @podarok thanks
