### ISSUE TITLE
BUG: Virtual Meetings with no description fail to load

### ISSUE THREAD

**Issue by froboy** [ymcatwincities/openy_gated_content#32]
To recreate (tested 14 Sept 2020 in sandbox):
- Edit a Virtual Meeting
- Remove the Description
- Navigate to the Virtual Meetings through the UI and click on the meeting
- Observe the detail page spins and doesn't load properly. 
- Observe `TypeError: this.description is null` in the console.

I believe removing `.processed` in this line would resolve the issue, but I'm not sure if that would break something else. https://github.com/ymcatwincities/openy_gated_content/blob/b125ff55511ba7da354f7164bfb1768796767fb8/js/gated-content/src/views/VirtualMeetingPage.vue#L161

FWIW, this behavior does NOT seem to happen with Live Stream content.

Alternatively, the Description field could be required if it should be so.

![Virtual_YMCA___Site-Install](https://user-images.githubusercontent.com/238201/93143818-504a2400-f6ae-11ea-9110-eb216fd73683.png)

**Comment by hamrant** [comment]
Fix - https://github.com/fivejars/openy_gated_content/pull/104/commits/5502eaac82daab1889497cccd745cfbb1e9abf76
PR - https://github.com/fivejars/openy_gated_content/pull/104

**Comment by froboy** [comment]
Quick visual review of the code looks good to me. Thanks @hamrant!

**Comment by hamrant** [comment]
Fix merged in fivejars fork, will be inclued to next release.
cc @froboy @anpolimus

**Comment by paige-kiecker** [comment]
Resolved in VY 1.0
