### ISSUE TITLE
Commas on video details page when only one category selected

### ISSUE THREAD

**Issue by jimparo** [ymcatwincities/openy_gated_content#33]
When viewing a video on the Virtual Y page videos with only a single category have a comma after the first category. This appears twice on the page, once below the instructor and a second time lower on the page above "up next".

The issue in on this page but it doesn't appear to be an issue in the sandbox right now.

https://sandbox-lily-std-virtual-y.openy.org/virtual-ymca#/video/f90fd2c6-aade-4432-9497-471c67d65539

**Comment by hamrant** [comment]
Fixed in https://github.com/fivejars/openy_gated_content/pull/141
