### ISSUE TITLE
Virtual Meeting - Instructor names of series not showing on instances

### ISSUE THREAD

**Issue by froboy** [ymcatwincities/openy_gated_content#39]
(As reported in Slack)

> As a site owner,
> When setting up a series,
> I want to see the instructor / host name display on all instances of the event

Recreation steps:

-  Create a recurring meeting
-  Load an individual instance of the meeting
-  Note the lack of host / instructor

Workaround: Edit each individual instance and add host name.

**Comment by paige-kiecker** [comment]
Resolved in VY 1.0
