### ISSUE TITLE
Refactor Zoom embeds 

### ISSUE THREAD

**Issue by froboy** [ymcatwincities/openy_gated_content#40]
As per Zoom - [iFrames are not officially supported](https://devforum.zoom.us/t/embed-code-on-htmlwebsite-page-for-zoom-streaming-directly-to/13350/5): "You can try using the iFrame method mentioned here, but it is not officially supported and can have some issues."

Proposed resolution:

1. ~Add "Embed Zoom" checkbox to Virtual Meeting content type. (off by default)~
```
if embed == false
  display button
else
  if link contains *zoom.us*
    iframe the link
  else
    display button
```
2. ~Add "Embed Zooms Default" option to Virtual Y Settings (off by default)~
3. ~Add language when/where Zoom embeds can be added that the Zoom embed functionality is experimental, not officially supported by Zoom, and thus we can't guarantee that it will function as desired.~
4. ~Modify Vue accordingly.~

After further discussion we've determined that this functionality is not being used for any Virtual Ys and is more buggy than not, so the Zoom embed functionality should be removed completely.

**Comment by froboy** [comment]
I'll be working on this this week.

**Comment by froboy** [comment]
I've been delayed on producing this PR. In the mean time if folks need a hotfix, this line https://github.com/ymcatwincities/openy_gated_content/blob/ddd13ddf5c824099b811245caf53e095e17714ac/js/gated-content/src/views/VirtualMeetingPage.vue#L157 can be changed to `return false;`

**Comment by froboy** [comment]
The Open Y team will be resolving this in the November release.

**Comment by hamrant** [comment]
Fixed in https://github.com/fivejars/openy_gated_content/pull/136
