### ISSUE TITLE
openy_gc_log: "Virtual Y Logs" is not restricted to a specific permission

### ISSUE THREAD

**Issue by froboy** [ymcatwincities/openy_gated_content#43]
https://github.com/fivejars/openy_gated_content/blob/a6b14795f5c86f58e0c0062198a9769c1c56d8e3/modules/openy_gc_log/config/install/views.view.virtual_y_logs.yml#L20-L22

Currently access is set to "Unrestricted". I'd recommend this View use the existing "View Log entity entities" permission.

To be clear, "Unrestricted" in still restricted to some level of administrator as the path contains `/admin`, but the view should still use a permission so it can be assigned to some better subset of users.

- [ ] Update permissions
- [ ] Add update hook

**Comment by froboy** [comment]
Fixed in https://github.com/fivejars/openy_gated_content/pull/129

**Comment by paige-kiecker** [comment]
Resolved in VY 1.0
