### ISSUE TITLE
YouTube Thumbnails occasionally display as pixelated grey box

### ISSUE THREAD

**Issue by froboy** [ymcatwincities/openy_gated_content#48]
Drupal will occasionally display a low resolution "grey box" image instead of a proper thumbnail. This seems to happen when the video is not high enough resolution.

For example:
https://i.ytimg.com/vi/m206494liG8/maxresdefault.jpg - grey box
https://i.ytimg.com/vi/m206494liG8/sddefault.jpg - smaller thumbnail that displays correctly
https://www.youtube.com/watch?v=m206494liG8 - original video

More info at https://stackoverflow.com/a/18029637/2566038
This seems like a default of the https://github.com/andrewvasilchuk/vue-lazy-youtube-video library that's being used and might need to be resolved there.

![Virtual_YMCA___YMCA_of_Northwest_Florida](https://user-images.githubusercontent.com/238201/96357024-9c2c2680-10bb-11eb-89b3-f6b78043f4a4.png)

**Comment by froboy** [comment]
I've confirmed that a temporary fix for this is adding a large (greater than 1280×720px) thumbnail via YouTube's video editor will resolve this issue.
![Video_details_-_YouTube_Studio](https://user-images.githubusercontent.com/238201/96749739-ce29db00-1390-11eb-9a6a-7b9435601610.png)

**Comment by hamrant** [comment]
@froboy can we close this issue? Looks like this not related to VY

**Comment by sarah-halby** [comment]
@hamrant & @froboy is this still an issue with the new video player? If it is not, let's close this issue.

**Comment by hamrant** [comment]
@sarah-halby I think this problem was on YouTube side, let's close issue after @froboy confirmation

**Comment by froboy** [comment]
I tested on the sandbox and the issue seems to be resolved with the new video player. I can't point to a specific commit, but it's good. 
![Virtual_YMCA___Drush_Site-Install](https://user-images.githubusercontent.com/238201/105873628-4c65d100-5fc1-11eb-901b-c16c1bbb624b.png)
