### ISSUE TITLE
Virtual Y is not Compatible with IE11

### ISSUE THREAD

**Issue by paige-kiecker** [ymcatwincities/openy_gated_content#51]
No elements of Virtual Y beyond the homepage render as intended within Virtual Y. Due to lack of official support from YouTube, and Microsoft ending support for Internet Explorer in 2021, full compatibility will not be supported by Open Y/Virtual Y.

Desired experience: add browser detection script that displays 
"Modern video experiences (such as YouTube) that power Virtual Y do not [support the internet browser](https://support.google.com/youtube/answer/175292?hl=en) you are using. Please consider upgrading to a [modern browser](https://browsehappy.com/) in order to continue enjoying videos and content on Virtual Y."
for users attempting to access Virtual Y using Internet Explorer.

**Comment by froboy** [comment]
It'd be nice to add Firefox... it's... the Open Source-y thing to do. :)

Or we could link to https://browsehappy.com/, which is a product of the WordPress team :) but seems to have good representation across the board.

**Comment by paige-kiecker** [comment]
@froboy noted, thank you!

**Comment by paige-kiecker** [comment]
This was resolved in v 1.1.3
