### ISSUE TITLE
Personify SSO redirect is jarring & inconstent with other providers

### ISSUE THREAD

**Issue by froboy** [ymcatwincities/openy_gated_content#52]
When I visit a Virtual Y site with Personify SSO I'm immediately taken away to Personify's (not super friendly) SSO authentication page. (See https://ymcasv.y.org or https://nmymca.y.org.) This removes any chance for the Y to communicate with the user before the authentication process begins.

![personify_redirect](https://user-images.githubusercontent.com/238201/97221689-416d8b80-179b-11eb-8e25-7d8cecc78c55.gif)

## Proposed behavior
Instead of an immediate redirect, Personify could present a "Log In" box just like every other provider which when clicked would direct the user to the SSO login flow, to allow for a more consistent experience. Alternatively an option could be put into place allowing site owners to select "Redirect immediately" or "Present login button".

**Comment by paige-kiecker** [comment]
This was resolved in v 1.1.3
