### ISSUE TITLE
Existing links for videos and blog posts are broken after 1.0 update

### ISSUE THREAD

**Issue by froboy** [ymcatwincities/openy_gated_content#54]
In VY 1.0 the paths for Video and Blog Post listings have changed. Existing links result in a 404 page and no automated upgrade path exists. 

Old path -> New Path
`/virtual-ymca#/categories` is now `/virtual-ymca#/categories/video`
`/virtual-ymca#/blog-post` is now `/virtual-ymca#/categories/blog` 

This was changed in https://github.com/fivejars/openy_gated_content/pull/104/files and then a fix was put in place in https://github.com/fivejars/openy_gated_content/pull/126/files.

I see two potential paths forward:
1. A post-update hook that searches menu links and paragraphs and rewrites any paths therein.
2. Additional routing to handle redirecting the old paths the the new.

**Comment by hamrant** [comment]
Fixed in https://github.com/fivejars/openy_gated_content/pull/156
