### ISSUE TITLE
Blog posts with no image have huge empty space

### ISSUE THREAD

**Issue by froboy** [ymcatwincities/openy_gated_content#57]
![Virtual_YMCA___Drush_Site-Install](https://user-images.githubusercontent.com/238201/98190568-e6474180-1edc-11eb-8420-a47ee4bccfe9.png)

To recreate:
- Edit a VY blog post
- Remove the image
- View the post

Seems like another unchecked null value. `<div class="blog-page__image" style="background-image: url(&quot;null&quot;);"></div>` is getting rendered and CSS applied as if there was an image there.

(tested on Carnation VY Sandbox 20201104)

**Comment by bharath-kondeti** [comment]
I have fixed the issue and raised the PR for the same.

https://github.com/fivejars/openy_gated_content/pull/166

**Comment by bharath-kondeti** [comment]
@froboy, I have worked on the fix and raised a fix for the same.

PR Link: https://github.com/fivejars/openy_gated_content/pull/166

**Comment by bharath-kondeti** [comment]
This issue is fixed and PR is merged to the repo 

Link: [https://github.com/fivejars/openy_gated_content/pull/166](https://github.com/fivejars/openy_gated_content/pull/166)

**Comment by podarok** [comment]
Thank you
