### ISSUE TITLE
Virtual Y Blog Posts do not use image style

### ISSUE THREAD

**Issue by froboy** [ymcatwincities/openy_gated_content#62]
In the same vein as https://github.com/ymcatwincities/openy/issues/2073, the VY Blog Post should use an image style instead of the user uploaded image. The `carnation_banner_1920_700` style may work here.

**Comment by sarah-halby** [comment]
@froboy this has been resolved in the VY Release 1.2. If you are still facing this issue, please raise it in Slack and we will address it.

**Comment by sarah-halby** [comment]
@froboy confirmed the issue was not resolved on 1/26. @paige-kiecker & I will work on prioritization.

**Comment by sarah-halby** [comment]
@froboy this will be included in the August 2021 release. If you need it early - it's available via the PR above.
