### ISSUE TITLE
Daxko and Personify SSO providers require cache_control_override

### ISSUE THREAD

**Issue by froboy** [ymcatwincities/openy_gated_content#63]
Enabling either `openy_gc_auth_daxko_sso` or `openy_gc_auth_personify_sso` can result in an issue where the Virtual Y homepage doesn't load. The only way around this is a Drupal cache clear, and then it only loads once. 

As per a Slack conversation, from @atiupa:
> In addition I recommend to install https://www.drupal.org/project/cache_control_override it fixes block/form caching issues in our case, we just fixed Daxko auth implementation with it, and going to add this module as dependency.

We've tested `cache_control_override` for both modules and it seems to resolve our issues. I'd second the addition of this module as a dependency to the SSO providers.

Todo:
- [ ] Add the dependency in the module's `.info.yml` files
- [ ] Enable the module in an update hook to ensure an upgrade path
- [ ] Add the dependency in composer somewhere?

**Comment by podarok** [comment]
@danylevskyi let's share Y North integration as an alternative for the alpha module dependency

**Comment by sarah-halby** [comment]
@anpolimus can you please review and make a final decision on this item and update the dev documentation? I'll get this added as a task in Jira.

**Comment by anpolimus** [comment]
@froboy , @podarok we have to recheck this issue. I've investigated this issue in December and added this fix:
https://github.com/ymcatwincities/openy_gated_content/blob/master/modules/openy_gc_auth/modules/openy_gc_auth_daxko_sso/openy_gc_auth_daxko_sso.module#L17
It looks like that we no longer need cache_control_override.
@froboy can you please check it at your instances?

**Comment by sarah-halby** [comment]
@froboy can you please review and verify per the comment above? We don't want to spend time on this for 1.4 if your issue is already addressed.

**Comment by froboy** [comment]
@sarah-halby confirmed. I believe @anpolimus's fix above resolved the issue. I'm closing this issue and we can reopen if it comes back.
