### ISSUE TITLE
Daxko Provider module doesn't update login form label or description

### ISSUE THREAD

**Issue by rdwash** [ymcatwincities/openy_gated_content#66]
For Daxko Provider implementation, updating the Form Label input from "Barcode" to anything else does not change the form label on the UI.

STEPS TO REPRODUCE:
Navigate to the Daxko Provider GC Auth settings:
- Manage > Virtual Y > Virtual Y Settings > GC Auth settings
- Find Daxko Provider and click Edit
- Update the Form Label value to something like "PIN Number"
- Save
- Log out 
- The login input label still says "Barcode"

Mitigation steps:
- Cleared the site cache and invalid functionality remains: The login input label still says "Barcode"

Possible point of error for Form label:
https://github.com/ymcatwincities/openy_gated_content/blob/master/modules/openy_gc_auth/modules/openy_gc_auth_daxko_barcode/src/Form/VirtualYDaxkoBarcodeLoginForm.php#L54

Possible point of error for Description value:
https://github.com/ymcatwincities/openy_gated_content/blob/224f4032dcc6950226b8533117516ffb3d76577c/modules/openy_gc_auth/modules/openy_gc_auth_daxko_barcode/src/Form/VirtualYDaxkoBarcodeLoginForm.php#L55

**Comment by froboy** [comment]
@bharath-kondeti

**Comment by sarah-halby** [comment]
@froboy is this issue resolved per the merge on Nov 30? If so, can you please close this issue?

**Comment by froboy** [comment]
@sarah-halby I don't have permission to close the issue, but I can confirm that https://github.com/fivejars/openy_gated_content/pull/179 resolved it.

**Comment by sarah-halby** [comment]
cc @rdwash on this one. Closing this ticket.
