### ISSUE TITLE
Shared content issues.

### ISSUE THREAD

**Issue by anpolimus** [ymcatwincities/openy_gated_content#68]
1. We have to add an additional field, called `Sync enabled`. Low 
2. Fix issue, when one of the source is failed. High
3. Test work with 0.7 Middle
4. Add ability to scan more than 50 items Medium
5. better documentation for Shared Content setup.

**Comment by sarah-halby** [comment]
Items 1,3,4,5 are all closed. 2. has been added as a separate bug in Jira backlog: https://openy.atlassian.net/browse/PRODDEV-228
