### ISSUE TITLE
"Add to Outlook" button puts `+` instead of spaces

### ISSUE THREAD

**Issue by froboy** [ymcatwincities/openy_gated_content#71]
- Visit a Live Stream or Virtual Meeting
- Click "Add to Outlook (or 365)"
- Observe the Title and body text is separated with `+`s instead of ` `s.

![Calendar_-_Schwab__Avi_-_Outlook](https://user-images.githubusercontent.com/238201/100142215-26a13c00-2e59-11eb-967c-cd8b146ff8aa.png)

**Comment by hamrant** [comment]
Let's close this one, seems to be fixed - https://github.com/fivejars/openy_gated_content/pull/193#issuecomment-742859172
