### ISSUE TITLE
Add "Login Mode" option to openy_gc_auth_daxko_sso

### ISSUE THREAD

**Issue by froboy** [ymcatwincities/openy_gated_content#73]
Similar to #52, the same method used in https://github.com/fivejars/openy_gated_content/pull/167 should be adapted for the Daxko SSO Gated Content Auth provider. 

**Acceptance criteria:**
- `/admin/openy/virtual-ymca/gc-auth-settings/provider/daxkosso` should have a "Login Mode" button
- the button should control whether SSO redirect happens immediately upon hitting the VY homepage or a button to log in is presented.

**Testing notes:**
- This may be hard to test fully as you'll need a valid Daxko SSO setup. It should be sufficient to take the configuration from an existing production site and see that you get to this error on your local: `CONFIGURATION ERROR: The value used as the 'redirect_uri' URL parameter is invalid because it is not an exact match against Daxko's white list of valid redirect uris.`

**Comment by sarah-halby** [comment]
@froboy this was completed in release 1.2.
