### ISSUE TITLE
Use email instead of uid in logs export

### ISSUE THREAD

**Issue by froboy** [ymcatwincities/openy_gated_content#74]
https://github.com/fivejars/openy_gated_content/pull/152 adds `uid` to the Logs Archive, but `uid` is not useful data to site owners without some translation. Let's use `email` instead, because it's either a real email or a fake one that owners could parse useful data from with a simple excel formula.

**Comment by podarok** [comment]
Export is done via Views, so this possibly could be done via Views tuning only

**Comment by froboy** [comment]
@podarok are you sure? It looks like there's custom code that generates the exports https://github.com/fivejars/openy_gated_content/pull/152/files#diff-2e89b91ef29ae86e4bd7de40053c36a84d761929ce86b9ad9c13b48243e90716R250

**Comment by podarok** [comment]
@froboy nice catch.
For sure Views should be used for generating export for consistency and maintenance simplicity

**Comment by froboy** [comment]
It looks like this was resolved in https://github.com/fivejars/openy_gated_content/pull/184. The code I referenced in 
https://github.com/fivejars/openy_gated_content/commit/f467113206ea4c2d71100895ca6f7a6d9f6398fe#diff-2e89b91ef29ae86e4bd7de40053c36a84d761929ce86b9ad9c13b48243e90716R269 may be deprecated? @podarok could check, but otherwise this issue could be considered resolved.

**Comment by hamrant** [comment]
@froboy yep, this was fixed and included to new release
