### ISSUE TITLE
YUSA GC Auth Testing Tweaks

### ISSUE THREAD

**Issue by froboy** [ymcatwincities/openy_gated_content#75]
A few issues from the YUSA testing that will will be resolved by the YUSA team:

**Documentation/UX**
- Permission mapping fieldset should have description noting a few things:
  - Contact YUSA if you need a list of the memberships your Y is sending to the Nationwide Membership database.
  - To remove a mapping, delete the text from the field and resave the form.
- The "Email Verification" fieldset should be closed by default.
- The "Association Number" field should be given a placeholder and/or description noting "9999" or "This is usually 4 digits."

**Mapping Logic**
- Permission mapping should have a wildcard (or simple regex) that allows Y's to allow membership types in bulk.
![Identity_Provider___Virtual_YMCA](https://user-images.githubusercontent.com/238201/101098746-11c75580-3589-11eb-9888-8ec8bb638170.png)

**Comment by sarah-halby** [comment]
@froboy have you fixed this issue and it's ready for testing?

**Comment by froboy** [comment]
https://github.com/fivejars/openy_gated_content/pull/192
https://github.com/fivejars/openy_gated_content/pull/230
those fixed two of these issues.

**Comment by anpolimus** [comment]
PR's were merged. Closing this ticket.
