### ISSUE TITLE
`virtual_ymca_editor` is unable to view category listings

### ISSUE THREAD

**Issue by froboy** [ymcatwincities/openy_gated_content#77]
To test:
- log in to https://sandbox-carnation-std-virtual-y.openy.org/ and create a user with the "Virtual YMCA Editor" role
- observe that as Administrator and Member, you can see these pages:
    - /virtual-ymca#/categories/blog
    - /virtual-ymca#/categories/video
- log in as the Editor
- Observe the above pages are empty, with no error or message.

**Comment by froboy** [comment]
PR coming

**Comment by hamrant** [comment]
Related PR - https://github.com/fivejars/openy_gated_content/pull/233

Issue was fixed, so let's close this one.
