### ISSUE TITLE
Long body text crashes outlook.com calendar links

### ISSUE THREAD

**Issue by froboy** [ymcatwincities/openy_gated_content#82]
If the url that is produced by the "Add to calendar" link for Office/Office 365 is more than 4096 characters then office.com will crash at the request. 

> As it appears that the entire body content is being encoded onto the URL, you could simply be hitting the default 4096 character buffer limit within the Microsoft system.

If you can find a way to trim the body text passed in the “add to office” link to something reasonable that should resolve the issue.

**To recreate**
- Create a virtual meeting or Live stream
- Add some long text to the Description field
- Visit the meeting as a member
- Click "Add to calendar" and select "Outlook"
- See this error from outlook.com and live.com
![Runtime_Error](https://user-images.githubusercontent.com/238201/101653179-aeb04580-3a04-11eb-886b-ae048b5bf95e.png)

**Comment by froboy** [comment]
@bharath-kondeti will be working on this.

**Comment by hamrant** [comment]
Looks like this was fixed, let's close this issue
