### ISSUE TITLE
ReClique CORE auth API: Members with multiple people on membership returns generic error to user

### ISSUE THREAD

**Issue by TomScarboroughYMCA** [ymcatwincities/openy_gated_content#85]
When attempting to use the "Open Y Virtual YMCA Auth ReClique" module, after confirming all module settings are correct, and the member email is valid *but* there are multiple people on the membership, the user is not granted gated access, no Watchdog error is logged, and the error "Something went wrong.  Please try again" is displayed to the user.

The API return JSON is: 
{"request_uri":"\/api\/v1\/members\/virtual_y\/?Email=xxxxx@xxxxx.com","status":"error","msg":"Looks like there is
more than 1 match"}

CORE only enables the 1 paying unit to have 1 login to their account for everyone.  So part of this issue is in ReClique's court.  But with that error message and nothing logged, this scenario is hard to react to properly.
<img width="311" alt="MoreThanOneUser error" src="https://user-images.githubusercontent.com/71293659/102400764-ff491500-3fa7-11eb-9f17-9dfa5072cda4.png">

Repro steps:

1. Enable the "Open Y Virtual YMCA Auth ReClique" module for a site using ReClique CORE crm.
2. Configure the module with correct API user credentials, and use the Production endpoint from Reclique.
3. Attempt member login using a valid email address that has multiple people on a membership.

**Comment by sarah-halby** [comment]
@TomScarboroughYMCA this issue will be resolved in the VY release 1.3.

**Comment by sarah-halby** [comment]
This issue was resolved with the ReClique SSO in VY 1.3.
