### ISSUE TITLE
Redirect issues

### ISSUE THREAD

**Issue by rajeshkeladimath** [ymcatwincities/openy_gated_content#86]
After updating to the latest version getting redirect issues. Getting the following message : The page isn’t redirecting properly and it is stuck under the redirect loop.This is happening after adding the landing page URLs in Virtual YMCA settings form '**admin/openy/virtual-ymca**'

![redirect](https://user-images.githubusercontent.com/8415953/102624764-7dedb000-416a-11eb-92cb-5ecb5f2f2a6c.png)

**Comment by rajeshkeladimath** [comment]
Hi team, 

Any updates on this yet.

**Comment by rajeshkeladimath** [comment]
Hi team,

We still have this issue with the daxko auth provider. This happens once we set "Virtual Y Landing Page url" and "Virtual Y Login Landing Page url" in Virtual YMCA settings form.

**Comment by rajeshkeladimath** [comment]
![Virtual-Y-settings-Whatcom-Family-YMCA](https://user-images.githubusercontent.com/8415953/105964109-c7a1b280-60a7-11eb-99a5-fd2d1ee1e355.png)

**Comment by sarah-halby** [comment]
Thank you @rajeshkeladimath -  we will add this to our next sprint for the VY 1.3 release. cc @froboy & @paige-kiecker

**Comment by anpolimus** [comment]
Hi, @rajeshkeladimath .
Can you please check the next:
1. Switch to the Dummy auth method and check if this issue still exist.
2. Check Daxko sso settings at:
/admin/openy/integrations/daxko/daxko-sso
?

**Comment by sarah-halby** [comment]
Per conversation on Slack on 3/24, this issue can be closed. https://openy.slack.com/archives/C01715RK630/p1616570541056500?thread_ts=1615987969.002600&cid=C01715RK630
