### ISSUE TITLE
Blogs don't work if a blog post has the 'category' field empty

### ISSUE THREAD

**Issue by akaleMulder** [ymcatwincities/openy_gated_content#91]
Making the 'category' field mandatory fixes the problem.
https://user-images.githubusercontent.com/2506214/103138054-dd166c00-46f8-11eb-8b6e-92df72c8fd7e.mp4

**Comment by sarah-halby** [comment]
@akaleMulder we'll add this to our backlog to address.

**Comment by akaleMulder** [comment]
@sarah-halby the issue has been fixed in the latest build.

**Comment by sarah-halby** [comment]
Hooray! Thanks, @akaleMulder cc @paige-kiecker - closing with this comment. Fixed in 1.2.1.
