### ISSUE TITLE
Autologout module throws error on cron

### ISSUE THREAD

**Issue by froboy** [ymcatwincities/openy_gated_content#95]
To recreate:
- Visit https://sandbox-carnation-std-virtual-y.openy.org
- Log in as admin, enable Autologout and Dblog modules
- Run cron
- Observe this error:

> Error: Call to undefined method Drupal\Core\Database\Driver\mysql\Select::limit() in openy_gc_autologout_users() (line 48 of /home/jenkins/workspace/SANDBOX_CARNATION_STANDARD_VIRTUAL_Y/build/docroot/modules/contrib/openy_gated_content/modules/openy_gc_autologout/openy_gc_autologout.module) 

According to this [helpful SO thread](https://drupal.stackexchange.com/a/260140/24177) `->limit(50)` should be `->range(0, 50)` in this case.

**Comment by sarah-halby** [comment]
@froboy this will be in the 1.2.1 release.
