### ISSUE TITLE
Log Archiver errors on export

### ISSUE THREAD

**Issue by froboy** [ymcatwincities/openy_gated_content#96]
To recreate:

- Enable the VY log module
- Create some recurring Live Streams/Virtual Meetings
- View those nodes through VY
- Change the recurrence so that those nodes are deleted from the db
- Attempt to export a log and see these errors

A few different errors may be thrown:

> Error: Call to a member function label() on null in Drupal\openy_gc_log\LogArchiver->prepareLogsForExport() (line 288 of modules/contrib/openy_gated_content/modules/openy_gc_log/src/LogArchiver.php).

> Error: Call to a member function get() on null in Drupal\openy_gc_log\LogArchiver->prepareLogsForExport() (line 289 of /var/www/docroot/modules/contrib/openy_gated_content/modules/openy_gc_log/src/LogArchiver.php)

It seems like in this case the logger is trying to pull the title from an expired event instance.

**Comment by sarah-halby** [comment]
@froboy this will be in the 1.2.1 release.
