### ISSUE TITLE
Second page of Shared Content Server results do not display

### ISSUE THREAD

**Issue by paige-kiecker** [ymcatwincities/openy_gated_content#97]
Not all of the videos in the shared content server are viewable by Ys 

Steps to reproduce:

1. Access shared content server, navigate to video tab
2. Click next on paginator
3. No results display on page two

Alternative  steps for similar issue: 
1. Access shared content server, navigate to video tab
2. Enter 'ymca' in donated by filter field, hit search
3. Click next on paginator
4. A small box displays on the next page, with the following
`[{"command":"insert","method":"prepend","selector":null,"data":"\u003Cdiv data-drupal-messages\u003E\n   \u003Cdiv role=\u0022contentinfo\u0022 aria-label=\u0022Error message\u0022 class=\u0022messages messages--error\u0022\u003E\n         \u003Cdiv role=\u0022alert\u0022\u003E\n                 \u003Ch2 class=\u0022visually-hidden\u0022\u003EError message\u003C\/h2\u003E\n                   An unrecoverable error occurred. The uploaded file likely exceeded the maximum file size (10 MB) that this server supports.\n               \u003C\/div\u003E\n     \u003C\/div\u003E\n   \u003C\/div\u003E\n","settings":null}]`

![vy_shared_content_filter](https://user-images.githubusercontent.com/48487047/104647107-016dc480-5677-11eb-8048-92e5470652b9.gif)

**Comment by sarah-halby** [comment]
We'll add this issue to the 1.3 release.

**Comment by hamrant** [comment]
Fixed in https://github.com/fivejars/openy_gated_content/pull/259
