### ISSUE TITLE
Enable scheduler for VY content types

### ISSUE THREAD

**Issue by froboy** [ymcatwincities/openy_gated_content#99]
The Scheduler module is enabled by default on VY sites but Virtual Y blog post and Virtual Y Video do not have it enabled. This should require no custom code, just some config changes to enable scheduled publishing of blogs and videos by default. See https://github.com/ymcatwincities/openy/blob/c31c7896308c52f9f3da4ae3d3e6310a4ae602ed/modules/openy_features/openy_node/modules/openy_node_landing/config/install/node.type.landing_page.yml#L12-L22 for default settings.

- Update config
- Add update hook

**Comment by sarah-halby** [comment]
Corresponds to task in Jira: https://openy.atlassian.net/browse/PRODDEV-198

**Comment by froboy** [comment]
This was reviewed and accepted into VY 1.3.
